@api = http://localhost:4001/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "userName": "JFERNANDEZ",
    "password": "909090"
}

### renovar token
{{api}}/login
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTE5NDQxYjNlMzBjMjJlNWJmYzRkMiIsImlhdCI6MTY0OTUxNDAxMiwiZXhwIjoxNjQ5NTI4NDEyfQ.yH6qk0uab1IzXE1C4_RNzIQfa4udjiiVFcqCCVg_wVM