@api = http://localhost:4001/api/users
@id = 62519441b3e30c22e5bfc4d2

### get all Users
{{api}}

### get User
{{api}}/{{id}}

#### create User
POST {{api}}
Content-Type: application/json

{
    "rolesId": [ "625193dcb3e30c22e5bfc4cf"],
    "firstName": "Jesus",
    "lastName": "Fernandez",
    "email": "jfernandez@correo.com",
    "userName": "JFERNANDEZ",
    "password": "909090"
}

### update User
PUT {{api}}/{{id}}
Content-Type: application/json

{
    "password": "123456"
}

### delete User 
DELETE {{api}}/{{id}}